<a href="https://colab.research.google.com/github/aymericCOUPRIE/DeepLearning/blob/main/TP_0_Rappels_python_et_Numpy_(sujet).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rappels de python et utilisation de Numpy

Les modèles d'apprentissage, comme beaucoup d'autres que vous verez (comme les modèles profonds), mettent en oeuvre des opérations sur les données d'entrées telles que des applications linéaires, des non-linéarités, des opérations d'aggrégation etc... Dans votre longue carrière d'expert en Machine Learning, vous serez donc souvent amenés à manipuler des jeux de données vectorielles et à effectuer toutes sortes d'opérations et calculs sur celles-ci. C'est pourquoi vous vous familliariserez dans un premier temps dans ce TP avec la librairie python $\texttt{numpy}$ qui implémente de multiples fonctions de calculs scientifiques.

Ce TP est divisé en deux parties. La première partie consiste simplement en un rappel des types de base en python (nombres entiers, flotant, booléens, liste) ainsi que des opérations élémentaires que l'on peut effectuer sur ces objets. Prenez un moment pour bien vérifier que ces opérations de bases vous soient bien acquises. La deuxième partie de l'exercice consiste à apprendre à effectuer des opérations sur les matrices et les vecteurs avec l'aide de la bibliothèque $\texttt{numpy}$, un outil crucial pour faire du calcul scientifique en python.

## Opérations et structures numériques de base en python

### Exemples d'operation sur les nombres

**Declarer un entier**

In [1]:
x = 3
print("x = %d" % x)
print("Le type de x est type(x): %s" % type(x)) 

x = 3
Le type de x est type(x): <class 'int'>


**Declarer un floatant**

In [2]:
y = 4.2
print("y = %d" % y)
print("y = %.1f" % y)
print("Le type de y est type(y): %s" % type(y)) 

y = 4
y = 4.2
Le type de y est type(y): <class 'float'>


**Exemples d'opérations**

In [3]:
#### Exemple d'addition
print("x + 1 = %d" % (x+1))

#### Exemple d'addition entre int et float (le resultat est au format float)
print("x + y = %.3f" % (x+y))     

#### Incrémentation
x += 2
print("La nouvelle valeur de x = %d" % x) 

### Puissance d'un entier
print("x a la puissance 2: x**2 = %d" % (x**2))

x + 1 = 4
x + y = 7.200
La nouvelle valeur de x = 5
x a la puissance 2: x**2 = 25


### Les booléens

In [4]:
t = True
f = False

print(type(f)) 
print(t and f) 
print(t or f)  
print(not t) 

x=3; y=2
print(x == y) 
print(x==3)  

<class 'bool'>
False
True
False
False
True


### Les listes

#### Declarer une liste vide

In [5]:
l_empty = []
print(l_empty)

[]


#### Declarer une liste contenant des éléments

In [6]:
l = [11, 5, 9, 10]
print(l)

[11, 5, 9, 10]


#### Acceder au i-eme element d'une liste

In [7]:
l[0]

11

#### Affichage du nombre d'element dans la liste

In [8]:
print("Le nombre d'elements dans l est len(l): %d" % len(l))
print("Le nombre d'elements dans l_empty est len(l_empty): %d" % len(l_empty))
print("Le dernier element de la liste est l[-1] = %d" % l[-1])

Le nombre d'elements dans l est len(l): 4
Le nombre d'elements dans l_empty est len(l_empty): 0
Le dernier element de la liste est l[-1] = 10


#### Parcourir les elements d'une liste

On boucle sur les elements de l pour les afficher un a un:

In [9]:
for i in range(len(l)):
    print(l[i])

11
5
9
10


In [10]:
for i in l:
    print(i)

11
5
9
10


On boucle sur les elements de l pour les afficher un à un avec leur indice correspondant avec la primitive 'enumerate'

In [11]:
for i, e in enumerate(l):
    print("Le %d eme element de la liste est l[%d] = %d" % (i, i, l[i]) )

Le 0 eme element de la liste est l[0] = 11
Le 1 eme element de la liste est l[1] = 5
Le 2 eme element de la liste est l[2] = 9
Le 3 eme element de la liste est l[3] = 10


## Manipulation des matrices et vecteurs avec Numpy

In [12]:
import numpy as np

Dans cet exercice, vous allez vous exercer à effectuer les opérations de bases nécéssaires pour apprendre les paramètres d'une régression linéaire ainsi qu'effectuer des prédictions à partir du modèle appris. Numpy est une bibliothèque logicielle open source qui fournit de multiples fonctions permettant notamment de manipuler et effectuer des opérations sur des structures matricielles et vectorielles. En Numpy, ces structures peuvent être obtenues à l'aide du même objet générique qui permet d'instancier n'importe quel tableau multidimensionnel : $\texttt{Ndarray}$.

$\texttt{Ndarray}$ est l'objet principal de NumPy, il s'agit d'une table d'éléments (généralement des nombres), tous du même type, indexés par un tuple d'entiers positifs (commençant par $0$, pas comme en Matlab). Les dimensions de la structure sont appelées axes. Ainsi, les vecteurs et les matrices peuvent être instanciés de manière générique avec un Ndarray comprenant respectivement 1 et 2 axes. 

### Opérations sur les vecteurs
Nous allons apprendre à créer et manipuler des vecteurs avec Numpy. Les premières lignes du code sont simplement à examiner pour comprendre les bases. Vous aurez ensuite à répondre à une série de questions pour apprendre à effectuer certaines opérations sur les vecteurs.

**Instancier des vecteurs :**
Il existe différentes manières de déclarer et instancier un vecteur d'un espace de dimension donnée. Les premières lignes de cette partie du code vous donnent différents exemples.

In [13]:
print("Instantiation d'un vecteur R^2 (2 dimension reelles):") 
np.ndarray(2)

Instantiation d'un vecteur R^2 (2 dimension reelles):


array([1.57423307e-316, 0.00000000e+000])

In [14]:
print("Vecteur nul dans R 2 (2 dimension reelles):") 
np.zeros(2)

Vecteur nul dans R 2 (2 dimension reelles):


array([0., 0.])

In [15]:
print("Vecteur remplie de 1 dans R 5:")   
np.ones(5)

Vecteur remplie de 1 dans R 5:


array([1., 1., 1., 1., 1.])

In [16]:
print("Vecteur dans R 4 contenant des valeurs aléatoires:")  #     
x = np.random.random(4)
print(x)

Vecteur dans R 4 contenant des valeurs aléatoires:
[0.85480936 0.29785793 0.09131576 0.34170354]


**Accès aux valeurs des vecteurs :** Les valeurs des tableaux Numpy sont accessibles de façon similaire aux listes simples en python. Gardez bien en tête que le système d'indiçage/indexation pour accéder aux éléments d'une liste/tableau se fait bien dans l'interval $[0;N-1]$ pour un tableau à N éléments. Il est également possible d'accéder et retourner en une seule ligne de commande aux plusieurs valeurs du vecteur en spécifiant un interval d'indices que l'on veut retourner. 

Par exemple, pour retourner de la composante (dimension) 2 à la composante 4 d'un vecteur:


In [17]:
y = x[2:4]  
print(y)

[0.09131576 0.34170354]


Le resultat est retourné sous la forme d'un nouveau vecteur y. On peut aussi retourner les 3 premières composantes du tableau comme suit:

In [18]:
print(x[:3])     # ici, ":3" signifie du 1er aux 3 eme élément inclus

[0.85480936 0.29785793 0.09131576]


ou bien retourner de la 3eme composante à la dernière comme ceci:

In [19]:
y = x[3:]     # ici, "3:" signifie daux 3 eme au dernier élément

ou encore les deux dernières cases :

In [20]:
y = x[-2:]
print(y)

[0.09131576 0.34170354]


**Récuperation de la dimension d'un vecteur:** examiner les dimensions du tableau numpy :


Ici, on montre que l'on peut accéder aux dimensions des axes du tableau multidimensionel avec \textit{shape}. Cette dernière renvoit sous les dimensions sous la forme d'un tuple. Dans notre cas, notre vecteur correspond à un tableau à un seul axe. La dimension d'un vecteur $\mathbf{x}$ peut donc être obtenue comme suit:

In [21]:
print(x.shape)  #La valeur de la dimension du 1er (et seul) axe du tableau

(4,)


**Parcours des valeurs du vecteur :**

Ici, on montre comment on peut boucler sur les éléments d'un vecteur de 3 façons: en itérant sur les indices puis acceder aux valeurs par les indices, en itérant directement sur les éléments du tableau, puis en itérant à la fois sur les indices ET les éléments avec enumerate.

Parcourez les valeurs du vecteur y avec en bouclant directement sur les elements du vecteur. Note ici on n'incremente plus directement sur les indices mais sur les element du vecteur, pour retrouver l'indice en cours, on doit faire l'incrementration a la main.

In [22]:
i=0
for x_i in x:
    print("La valeur de la %d eme composante est: %f" % (i,x_i))
    i += 1

La valeur de la 0 eme composante est: 0.854809
La valeur de la 1 eme composante est: 0.297858
La valeur de la 2 eme composante est: 0.091316
La valeur de la 3 eme composante est: 0.341704


Faites la meme chose avec la fonction enumerate pour avoir acces aux indices sans faire d'incrementation

In [23]:
for i, x_i in enumerate(x):
    print("La valeur de la %d eme composante est: %f" % (i,x_i))

La valeur de la 0 eme composante est: 0.854809
La valeur de la 1 eme composante est: 0.297858
La valeur de la 2 eme composante est: 0.091316
La valeur de la 3 eme composante est: 0.341704


**Recuperez les n derniere composante composantes**

Recuperez les 3 derniere composante composantes avec x[dim-3:] ou x[-3:] (on va de la composante dim-3 à la dernière (:):

In [24]:
dim = x.shape[0]
print( x[dim-3:] )
print(x[-3:])

[0.29785793 0.09131576 0.34170354]
[0.29785793 0.09131576 0.34170354]


Recuperez les composantes de 3 a la derniere

In [25]:
print(x[3:])

[0.34170354]


Recuperez les composantes alant de l'indice 3 a 7

In [26]:
print(x[3:7])

[0.34170354]


### PARTIE QUESTIONS : A VOUS DE JOUER !
Dans cette partie vous serez amenés à utiliser certaines fonctions de calcul numpy très pratiques pour effectuer des opération d'algèbre linéaire tel qu'un produit scalaire entre deux vecteurs $\mathbf{x}$ et $\mathbf{y}$ (avec np.dot(x,y)). Nous verrons par la suite qu'étant donnée que le ndarray est un objet générique cette fonction "produit scalaire" de numpy peut également être utilisé pour les produits matriciels.

Soit les deux vecteurs suivant:

In [27]:
x = np.random.normal(0,1,size=4)
y = np.random.normal(0,1,size=4)
print(x, y)

[-1.36180816  0.87536976 -1.12987826  0.74665225] [-0.01355987  0.31267231 -0.75921794 -0.71721743]


1) Addition des vecteur: x + y:

In [28]:
print(x + y)

[-1.37536803  1.18804207 -1.88909619  0.02943482]


2) Combinaison lineaire des vecteurs 4.2 * x + 1.2 * y:

In [29]:
print(4.2 * x + 1.2 * y)

[-5.73586612  4.05175975 -5.6565502   2.27527852]


3) Lister avec une boucle les elements de x a la puissance 2:

In [30]:
for i in x:
  print(pow(i, 2))

1.8545214693780778
0.7662722132678439
1.276624875696221
0.5574895764972039


4) Generer et mettre dans un vecteur elements de x a la puissance 2 en une seule commande:

In [31]:
z = [pow(i, 2) for i in x]
print(z)

[1.8545214693780778, 0.7662722132678439, 1.276624875696221, 0.5574895764972039]


5) La somme des elements de x avec une boucle:

In [32]:
sum = 0
for i in x:
  sum += i
print(sum)

-0.8696644147091606


6) La somme des elements de x avec la primitive 'sum' de numpy:

In [33]:
print(np.sum(x))

-0.8696644147091606


7) Calculer la norme L_2 de x avec une boucle en utilisant les points 3 et 5:

In [34]:
sum2 = 0
for i in x:
  sum2 += pow(i, 2)

print(sum**0.5)

nan


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in double_scalars
  """


8) Calculer la norme L_2 de x sans boucle en utilisant les points 4 et 6:

In [35]:
print(np.sqrt(np.sum([i**2 for i in x])))

2.110665329899401


9) Calculer le produit scalaire entre x et y avec une boucle:

In [36]:
prd_sc = 0
for i, j in zip(x, y):
  prd_sc += i * j

print(prd_sc)

0.6144816595627842


11) Calculer le produit scalaire entre x et y avec la primitive 'dot' de numpy:

In [37]:
print(np.dot(x, y))

0.6144816595627842


## Opérations sur les matrices
Cette partie est similaire à la précédente, un point général sur la manière d'instancier les objets sera d'abord fait, puis, vous répondrez à une série de questions en implémentant les bouts de codes demandés.

On notra simplement que la différence avec l'instantiation d'un vecteur consiste à préciser les dimensions de deux axes du tableau numpy au lieu d'un seul et que l'accès se fait (presque) maintenant comme pour un tableau classique à deux entrées:

**Matrice nulle dans 2x2: M1 = np.zeros((2,2))**

In [38]:
M1 = np.zeros((2,2))
print(M1)  

[[0. 0.]
 [0. 0.]]


**Matrice 3x3 remplie de 1: M2 = np.ones((3,3))  :**

In [39]:
M2 = np.ones((3,3)) 
print(M2)  

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Matrice 4x4 aleatoire: M3 = np.random.random((4,4))**

In [40]:
M3 = np.random.random((4,4))
print(M3)

[[0.25569372 0.38545969 0.29093126 0.60287414]
 [0.18768927 0.62869426 0.02148331 0.11585732]
 [0.22951308 0.84164517 0.24227616 0.90105637]
 [0.20411349 0.5975937  0.01437214 0.62874606]]


**Matrice identite 5x5: M4 = np.eye(5,5) :**

In [41]:
M4 = np.eye(5,5) 
print(M4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Trouver les dimensions du Numpy array: **

Soit deux matrices 4x4 M1 et M2

In [42]:
M1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [9,10,11,8]])
M2 = np.array([[9,10,11,3], [5,6,7,8], [1,2,3,8], [9,10,11,7]])

print(M1)
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 9 10 11  8]]
[[ 9 10 11  3]
 [ 5  6  7  8]
 [ 1  2  3  8]
 [ 9 10 11  7]]


**Donnez les dimensions de la matrice M1**

In [43]:
size = M1.shape
nb_lignes = size[0]    
nb_colones= size[1]

print(size)
print(M1)

(4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 9 10 11  8]]


### Parcours des valeurs de la matrice

In [44]:
for i in range(nb_lignes):
    for j in range(nb_colones):
        print("La valeur de la composante %d%d est:  = %f" % (i, j, M1[i,j]))

La valeur de la composante 00 est:  = 1.000000
La valeur de la composante 01 est:  = 2.000000
La valeur de la composante 02 est:  = 3.000000
La valeur de la composante 03 est:  = 4.000000
La valeur de la composante 10 est:  = 5.000000
La valeur de la composante 11 est:  = 6.000000
La valeur de la composante 12 est:  = 7.000000
La valeur de la composante 13 est:  = 8.000000
La valeur de la composante 20 est:  = 9.000000
La valeur de la composante 21 est:  = 10.000000
La valeur de la composante 22 est:  = 11.000000
La valeur de la composante 23 est:  = 12.000000
La valeur de la composante 30 est:  = 9.000000
La valeur de la composante 31 est:  = 10.000000
La valeur de la composante 32 est:  = 11.000000
La valeur de la composante 33 est:  = 8.000000


**Donnez la valeure de l'element de la 1er ligne et 3 eme colone de M1**

In [45]:
M1[0,2]

3

**Parcourez les valeur de la matrice M2 avec en bouclant sur les indices**

In [46]:
for i in range(M1.shape[0]):
    for j in range(M1.shape[1]):
        print("La valeur de la composante M1_%d%d est:  = %d" % (i, j, M1[i,j]))

La valeur de la composante M1_00 est:  = 1
La valeur de la composante M1_01 est:  = 2
La valeur de la composante M1_02 est:  = 3
La valeur de la composante M1_03 est:  = 4
La valeur de la composante M1_10 est:  = 5
La valeur de la composante M1_11 est:  = 6
La valeur de la composante M1_12 est:  = 7
La valeur de la composante M1_13 est:  = 8
La valeur de la composante M1_20 est:  = 9
La valeur de la composante M1_21 est:  = 10
La valeur de la composante M1_22 est:  = 11
La valeur de la composante M1_23 est:  = 12
La valeur de la composante M1_30 est:  = 9
La valeur de la composante M1_31 est:  = 10
La valeur de la composante M1_32 est:  = 11
La valeur de la composante M1_33 est:  = 8


**Parcourez les vecteurs lignes de la matrice M2 en bouclant directement sur les elements du vecteur**

In [47]:
for v_i in M2:
    print(v_i)

[ 9 10 11  3]
[5 6 7 8]
[1 2 3 8]
[ 9 10 11  7]


**Parcourez les vecteurs colonnes de la matrice M2 en bouclant directement sur les elements du vecteur**

Astuce, baladez vous dans les vecteurs lignes de la transpose de la matrice.

In [48]:
for v_j in np.transpose(M2):
    print(v_j)

[9 5 1 9]
[10  6  2 10]
[11  7  3 11]
[3 8 8 7]


**Recuperez les 2 premier vecteurs ligne de M1 en une seule ligne de commande**

Quand on ne specifie pas les indices des 2 champs, on a implcitement access aux indices des lignes seuls

In [49]:
M1[:2] #Equivalent a M1[:2 , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Recuperer en une seule ligne de commande les 2 derniers vecteurs colones de la matrices M1**

Ici on veut agir sur les colonnes, on doit donc specifer les intervals sur les lignes ET les colones.

In [50]:
nb_col = M1.shape[1]
M1_transpose = np.transpose(M1)
print(M1_transpose[nb_col - 2:])

[[ 3  7 11 11]
 [ 4  8 12  8]]


 ### PARTIE QUESTIONS : A VOUS DE JOUER !

Dans les questions, vous aurez à comprendre comment on effectue un produit matriciel entre deux matrices ou bien entre une matrice et un vecteur. Vous verrez deux manières de procéder: avec une boucle, et avec la primitive $\texttt{dot(,)}$ de $\texttt{numpy}$. Le script vous permet de calculer le temps mis pour effecteur ces deux calculs. Pensez bien à écrire votre code entre les deux instructions suivante:

In [51]:
import time
start_time = time.time()
# Votre code pour le produit matricielle ici
stop_time =  time.time()

Comme vous le verrez, la fonction numpy dot est beaucoup plus rapide que votre implémentation à base de boucles car cette fonction optimise très bien les calculs de nature vectorielle. C'est pourquoi il sera toujours intéressant d'écrire vos équations en notation vectorielle afin de les implementer simplement et efficacement par la suite. \\

\noindent \textbf{Note importante: } L'important à retenir est qu'on peut considérer une matrice soit comme une application linéaire soit comme un ensemble de vecteurs (chaque ligne correspond à un vecteur d'apprentissage par exemple). Le produit matricielle entre une matrice $\mathbf{M1}$ de dimensions $n$ x $k$ ($n$ lignes et $k$ colonnes) et une autre $\mathbf{M2}$ de dimension $k$ x $m$ donnera un résultat $\mathbf{M1}\mathbf{M2}$ (calculé avec np.dot(M1,M2)) de dimensions $n$ x $m$. Autremment dit le nombre de colonnes de la première matrice doit être égale au nombre de lignes de la deuxième matrice. Un vecteur $\mathbf{x} \in \mathbb{R}^d$ correspond à une matrice de dimension $d$ x $1$. On pourra donc calculer le resultat de l'application linéaire décrite par la matrice $\mathbf{M}$ de dimensions $n$ x $d$ sur le vecteur $\mathbf{x}$ de dimensions $d$ x $1$ avec np.dot(M,x). Le résultat sera un vecteur $\mathbf{y} \in \mathbb{R}^n$ (représenté par un tableau de dimensions $n$ x $1$). \\

\noindent \textbf{Intuitivement}, appliquer linéairement $\mathbf{M}$ de dimensions $n$ x $d$ à $\mathbf{x} \in \mathbb{R}^d $ revient à "\textit{empiler}" les résultats des produits scalaires entre $\mathbf{x}$ et chacun des vecteurs colonne de $\mathbf{M}$. Si il y a $n$ colonnes, il y aura donc $n$ produits scalaires et donc $n$ valeurs dans le vecteur résultats. Les composantes du vecteur résultat correspondent ainsi aux similarités (au sens de la métrique du produit scalaire) entre $\mathbf{x} \in  \mathbb{R}^d$ et une base de $n$ vecteurs dans $\mathbb{R}^d$.


1) Addition de M1  M2:

In [52]:
print(M1 + M2)

[[10 12 14  7]
 [10 12 14 16]
 [10 12 14 20]
 [18 20 22 15]]


2) Multiplication terme a terme de M1  M2:

In [53]:
print(M1 * M2)

[[  9  20  33  12]
 [ 25  36  49  64]
 [  9  20  33  96]
 [ 81 100 121  56]]


3) Afficher avec une boucle les elements de M1 a la puissance 2:

In [54]:
for i in M1:
  for j in i:
    print(j**2)

1
4
9
16
25
36
49
64
81
100
121
144
81
100
121
64


4) Generer la matrice M3 contenant les elements de M1 a la puissance 2 en une seule commande:

In [55]:
M3 = M1**2
print(M3)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [ 81 100 121  64]]


5) La somme des elements de M1 avec une boucle:

In [56]:
sum = 0
for i in M1:
  for j in i:
    sum += j

print(sum)

116


6) La somme des elements de M1 avec la primitive 'sum' de numpy:

In [57]:
np.sum(M1)

116

7) Cherchez dans vos souvenir ou sur internet et implementez la formule permettant de calculer le produit matricielle (different du produit terme a terme !) entre M1 et M2 avec une boucle:

In [68]:
#On va calculer le temps que cela met avec une boucle
#On comparera par la suite ce temps avec celui prit par une autre methode
start_time = time.time()
M1M2 = np.zeros(M1.shape)       
print(M1M2.shape)
## Your code here

for i in range(M1M2.shape[0]):
    for j in range(M1M2.shape[1]):
        prodScal=0
        for k in range(0,M1.shape[0]):
            prodScal+=M1[i,k]*M2[k,j]
        M1M2[i,j]=prodScal

stop_time =  time.time()

print(M1M2)
print("\nTemps de calcul = %f secondes" % (stop_time - start_time))

(4, 4)
[[ 58.  68.  78.  71.]
 [154. 180. 206. 175.]
 [250. 292. 334. 279.]
 [214. 252. 290. 251.]]

Temps de calcul = 0.007174 secondes


8) Calculer le produit matricielle entre M1 et M2 avec la primitive 'dot' de numpy:

In [69]:
start_time = time.time()
# Your code here
M1M2 = np.dot(M1, M2)       #retourner le resultat
stop_time =  time.time()

print(M1M2)
print("\nTemps de calcul = %f secondes" % (stop_time - start_time))

[[ 58  68  78  71]
 [154 180 206 175]
 [250 292 334 279]
 [214 252 290 251]]

Temps de calcul = 0.000160 secondes


9) Soit la matrice M3 suivante (aleatoire mais ce n'est pas ce qui est important ici). Calculer le produit matricielle entre M1 et M3 avec la primitive 'dot' de numpy (attention aux dimensions des deux matrices !) :

In [60]:
M3 = np.random.random((10,4)) 
print(np.dot(M3, M1))

[[17.72730349 20.62735757 23.52741165 23.13697303]
 [14.52324302 16.3592428  18.19524257 16.83113492]
 [21.95929293 25.62944588 29.29959882 29.27828077]
 [16.28670885 19.28755127 22.2883937  23.75426679]
 [12.70983648 14.33256634 15.95529621 15.09352375]
 [ 5.50918978  6.22333007  6.93747037  5.6969445 ]
 [13.86143902 16.1253096  18.38918018 16.99665997]
 [ 9.48759491 11.49516024 13.50272558 14.03071117]
 [ 9.85490954 11.13609131 12.41727308 11.60006114]
 [12.38834495 14.60675756 16.82517016 18.59651385]]


11) Calculer le produit matricielle entre <x , M3> avec la primitive 'dot' de numpy:

In [65]:
print(np.dot(M3, x))

[-1.21445216  0.41107534 -1.0812986  -1.38093986  0.08733568  0.36353197
 -0.92456051 -0.36479382 -0.06335841 -1.49040907]


12) Calculer le produit matricielle entre <M3 , x> avec la primitive 'dot' de numpy (qu'est ce qui change ?) :")
HINT: Pensez à la transposée de vos structures pour aligner leurs dimensions !

In [ ]:
print(np.dot(M3, np.transpose(x)))